<<<<<<< HEAD
# .github/workflows/main.yaml
name: Deploy Flask API

on:
  push:
    branches: [main]
=======
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
>>>>>>> 17b5f132d4177f1e7880cc3fdf6ba5a8bef6abcc

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
=======

>>>>>>> 17b5f132d4177f1e7880cc3fdf6ba5a8bef6abcc
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
<<<<<<< HEAD
          python-version: '3.11'
=======
          python-version: '3.10'  # or your python version
>>>>>>> 17b5f132d4177f1e7880cc3fdf6ba5a8bef6abcc

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

<<<<<<< HEAD
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
=======
      - name: Run tests
        run: |
          # Replace with your actual test command
          # For example, if you use pytest:
          pytest || echo "No tests found or tests skipped"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

>>>>>>> 17b5f132d4177f1e7880cc3fdf6ba5a8bef6abcc
      - name: Deploy to Render
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
<<<<<<< HEAD
          curl -X POST https://api.render.com/deploy/srv-${{ env.RENDER_SERVICE_ID }}/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY"
=======
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            "https://api.render.com/deploy/srv-$RENDER_SERVICE_ID"
>>>>>>> 17b5f132d4177f1e7880cc3fdf6ba5a8bef6abcc
